apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name}}-wordpress-ingress
spec:
  tls:
  - hosts:
    - {{.Values.ingress.hostname | default "babak-ghiyasvand-nl-rg3.maxtld.dev"}}
    secretName: letsencrypt
  ingressClassName: {{ .Values.ingress.classname }}
  rules:
    - host: {{.Values.ingress.hostname | default "babak-ghiyasvand-nl-rg3.maxtld.dev"}}
      http:
        paths:
          - path: /wordpress
            pathType: Prefix
            backend:
              service:
                name: {{.Values.wordpress.svc.name | default "wordpress"}}
                port:
                  number: 80
    - host: {{.Values.ingress.hostname | default "babak-ghiyasvand-nl-rg3.maxtld.dev"}} 
      http:
        paths:
          - path: /dbadmin
            pathType: Prefix
            backend:
              service:
                name: {{.Values.phpadmin.svc.name | default "phpmyadmin-svc"}} 
                port:
                  number: 80