apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name}}-wordpress-ingress
spec:
  ingressClassName: {{ .Values.ingress.classname }}
  rules:
    - host: {{.Values.wordpress.ingress.host | default "wordpress.local.com"}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{.Values.wordpress.svc.name | default "wordpress"}}
                port:
                  number: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name}}-phpadmin-ingress
spec:
  ingressClassName: {{ .Values.ingress.classname }}
  rules:
    - host: {{.Values.phpadmin.ingress.host | default "phpadmin.local.com"}} 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{.Values.phpadmin.svc.name | default "phpmyadmin-svc"}} 
                port:
                  number: 80