apiVersion: v1
kind: Service
metadata:
  name: {{.Values.mysql.svc.name | default "wordpress-mysql"}}
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None