apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}-wordpress-deploy
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      
          
      - image: {{.Values.registery | default "docker.io"}}/{{ .Values.wordpress.image.repository | default "wordpress"}}:{{ .Values.wordpress.image.tag | default "6.2.1-apache" }}
        name: wordpress
        env:
        - name: WORDPRESS_DB_NAME
          value: {{ .Values.mysql.dbname | default "wordpress-mysql"}}
        - name: WORDPRESS_DB_HOST
          value: {{.Values.mysql.svc.name | default "wordpress-mysql"}}
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: WORDPRESS_DB_USER
          value: {{ .Values.mysql.dbuser | default "wordpress"}}
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html/wordpress
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Values.wordpress.pvc.name | default "wp-pv-claim"}}


