apiVersion: v1
kind: Service
metadata:
  name: {{.Values.wordpress.svc.name | default "wordpress"}}
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: {{ .Values.wordpress.svc.type | default "ClusterIP" }}