registery: 
ingress:
  classname: nginx-ingress 
  hostname: 

wordpress:
  image:
    repository: devopshttp/wordpress
    tag: v1 # default wordpress:6.2.1-apache
  pvc:
    name:  #Set wordpress pvc name
    size:  #Set wordpress storage size default is 2Gi
  svc:
    name: 
    type: ClusterIP
  ingress:
    host: wordpress.agri-bank.com

mysql:
  image:
    tag: ""
  # Set WordPress DB name  default wordpress-mysql
  dbname: "" 
  # Set Wordpress DB username default wordpress
  dbuser: "" 
  pvc:
    name: "" #Set MYSQL pvc name
    size: "" #Set MYSQL storage size default is 2Gi
  svc:
    name: ""
  # MYSQL root password  
  root_password: 

phpadmin:
  image:
    repository: devopshttp/phpadmin
    tag: v1
  svc:
    name:
    type:
  ingress:
    host: phpadmin.agri-bank.com

 